"""
Django settings for pharmaconnect project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Charger les variables d'environnement depuis .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oux^15ge06mwt%czc5f^mc0*pvq$cs0x6n9az#l7il%#ovf)&f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'pharmacies',
    'wholesalers',
    'anticounterfeit',
    'orders',
    'patients',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmaconnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmaconnect.wsgi.application'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# ==============================================
# CONFIGURATION BASE DE DONNÉES - PostgreSQL
# ==============================================

# Récupération des variables depuis .env
DB_USER = os.getenv('DB_USER', 'postgres')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_NAME = os.getenv('DB_NAME', 'Meditrack')

# Configuration PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

# Alternative avec DATABASE_URL (si vous préférez)
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL'),
#         conn_max_age=600
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'  # Changé en français

TIME_ZONE = 'Africa/Douala'  # Changé pour le Cameroun

USE_I18N = True

USE_TZ = True


# ==============================================
# CONFIGURATION EMAIL (depuis le fichier .env)
# ==============================================

# Email configuration
if DEBUG:
    # En développement, on affiche les emails dans la console pour éviter les erreurs
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("📧 Mode développement : Les emails seront affichés dans la console")
else:
    # En production, on utilise le serveur SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('MAIL_SERVER', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('MAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('MAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.getenv('MAIL_USE_SSL', 'False') == 'True'
    EMAIL_HOST_USER = os.getenv('MAIL_USERNAME')
    EMAIL_HOST_PASSWORD = os.getenv('MAIL_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    
    # Vérifier que les variables sont définies
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        print("⚠️  ATTENTION : Les variables MAIL_USERNAME et MAIL_PASSWORD doivent être définies dans .env")


# ==============================================
# AUTRES CONFIGURATIONS
# ==============================================

# Redirection après connexion/déconnexion
LOGIN_URL = 'auth:login'
LOGIN_REDIRECT_URL = 'auth:dashboard'
LOGOUT_REDIRECT_URL = 'auth:login'

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Media files (pour les uploads de documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_COOKIE_SECURE = False  # Mettre à True en production avec HTTPS
SESSION_ENGINE = 'django.contrib.sessions.backends.db'