"""
Django settings for pharmaconnect project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Charger les variables d'environnement depuis .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'pharmacies',
    'wholesalers',
    'anticounterfeit',
    'orders',
    'patients',
    'pwa',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmaconnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmaconnect.wsgi.application'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# ==============================================
# CONFIGURATION BASE DE DONNÉES - PostgreSQL
# ==============================================

# Récupération des variables depuis .env
DB_USER = os.getenv('DB_USER', 'postgres')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
DB_NAME = os.getenv('DB_NAME', 'Meditrack')

# Configuration PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}

# Alternative avec DATABASE_URL (si vous préférez)
# import dj_database_url
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL'),
#         conn_max_age=600
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# ==============================================
# CONFIGURATION EMAIL
# ==============================================

if os.getenv('EMAIL_BACKEND_CONSOLE', 'False') == 'True':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print(" Mode console : Les emails seront affichés dans la console (aucun envoi réel)")
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('MAIL_SERVER', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('MAIL_PORT', 587))

    # Gestion cohérente TLS / SSL (on ne peut pas avoir les deux)
    use_tls = os.getenv('MAIL_USE_TLS', 'True') == 'True'
    use_ssl = os.getenv('MAIL_USE_SSL', 'False') == 'True'
    if use_tls and use_ssl:
        # Si les deux sont True, on privilégie TLS (car c'est le plus standard)
        use_ssl = False
        print("⚠️  MAIL_USE_TLS et MAIL_USE_SSL sont tous les deux True. On privilégie TLS.")
    EMAIL_USE_TLS = use_tls
    EMAIL_USE_SSL = use_ssl

    EMAIL_HOST_USER = os.getenv('MAIL_USERNAME')
    EMAIL_HOST_PASSWORD = os.getenv('MAIL_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('MAIL_DEFAULT_SENDER', EMAIL_HOST_USER)

    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        print("⚠️  ATTENTION : Les variables MAIL_USERNAME et MAIL_PASSWORD doivent être définies dans .env")
    else:
        print(f" Configuration SMTP : {EMAIL_HOST}:{EMAIL_PORT} TLS={EMAIL_USE_TLS} SSL={EMAIL_USE_SSL}")


# ==============================================
# AUTRES CONFIGURATIONS
# ==============================================

# Redirection après connexion/déconnexion
LOGIN_URL = 'auth:login'
LOGIN_REDIRECT_URL = 'auth:dashboard'
LOGOUT_REDIRECT_URL = 'auth:login'

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Media files (pour les uploads de documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'  # Mettre à True en production avec HTTPS
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================
# CONFIGURATION PWA (django-pwa)
# ==============================================

PWA_APP_NAME = 'PharmaConnect'
PWA_APP_DESCRIPTION = "Gestion de pharmacie anti-contrefaçon"
PWA_APP_THEME_COLOR = '#2E8B57'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/pharmacies/dashboard/'
PWA_APP_ICONS = [
    {'src': '/static/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_ICONS_APPLE = [
    {'src': '/static/icons/icon-192x192.png', 'sizes': '192x192'}
]
PWA_APP_SPLASH_SCREEN = []
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'fr-FR'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static', 'js', 'serviceworker.js')
