# Generated by Django 6.0.7 on 2026-07-31 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anticounterfeit', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='qrcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticounterfeit.qrcode'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
