# Generated by Django 6.0.7 on 2026-08-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticounterfeit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='code',
            field=models.CharField(default='CM0000', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticounterfeit.medicine'),
        ),
    ]
