# Generated by Django 6.0.7 on 2026-08-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/'),
        ),
    ]
