# Generated by Django 6.0.7 on 2026-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète (rue, quartier, ville, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (coordonnées GPS)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (coordonnées GPS)', null=True),
        ),
    ]
